import type { Place } from '@/types';

export const MOCK_PLACES: Place[] = [
  {
    id: '1',
    name: '라이더스 카페',
    description: '바이커들의 아지트. 넓은 주차장과 헬멧 보관함 완비.',
    category: 'cafe',
    latitude: 37.5485,
    longitude: 127.0455,
    address: '서울 성동구 성수동 123',
    phone: '02-1234-5678',
    photos: [],
    rating: 4.5,
    reviewCount: 128,
    tags: ['넓은주차장', '헬멧보관', '와이파이'],
    openingHours: '09:00 - 22:00',
    parkingInfo: '바이크 전용 주차 20대',
    submittedBy: 'admin',
    approved: true,
    createdAt: '2026-01-15',
  },
  {
    id: '2',
    name: '팔당 뷰 카페',
    description: '한강 뷰가 멋진 라이딩 명소. 주말엔 바이커들로 가득.',
    category: 'cafe',
    latitude: 37.5210,
    longitude: 127.2810,
    address: '경기 하남시 팔당로 456',
    photos: [],
    rating: 4.8,
    reviewCount: 256,
    tags: ['한강뷰', '넓은주차장', '포토존'],
    openingHours: '10:00 - 21:00',
    parkingInfo: '바이크 주차 50대+',
    submittedBy: 'admin',
    approved: true,
    createdAt: '2026-01-20',
  },
  {
    id: '3',
    name: '북악 정비소',
    description: '북악 스카이웨이 근처 오토바이 전문 정비소.',
    category: 'repair_shop',
    latitude: 37.6000,
    longitude: 126.9800,
    address: '서울 종로구 북악산로 789',
    phone: '02-9876-5432',
    photos: [],
    rating: 4.2,
    reviewCount: 67,
    tags: ['타이어교체', '오일교환', '긴급정비'],
    openingHours: '08:00 - 19:00',
    submittedBy: 'admin',
    approved: true,
    createdAt: '2026-02-01',
  },
  {
    id: '4',
    name: '양평 휴게소',
    description: '6번 국도 라이딩 중 쉬어가기 좋은 곳.',
    category: 'rest_stop',
    latitude: 37.4915,
    longitude: 127.4875,
    address: '경기 양평군 양평읍 345',
    photos: [],
    rating: 3.9,
    reviewCount: 45,
    tags: ['화장실', '자판기', '그늘막'],
    parkingInfo: '넓은 주차장',
    submittedBy: 'admin',
    approved: true,
    createdAt: '2026-02-10',
  },
  {
    id: '5',
    name: '남산 뷰포인트',
    description: '서울 야경을 한눈에. 야간 라이딩 필수 코스.',
    category: 'viewpoint',
    latitude: 37.5512,
    longitude: 126.9882,
    address: '서울 용산구 남산공원길 100',
    photos: [],
    rating: 4.7,
    reviewCount: 312,
    tags: ['야경', '포토존', '야간라이딩'],
    parkingInfo: '바이크 주차 가능',
    submittedBy: 'admin',
    approved: true,
    createdAt: '2026-02-15',
  },
  {
    id: '6',
    name: 'S-OIL 한남점',
    description: '한남대교 근처 주유소. 바이크 주유 편리.',
    category: 'gas_station',
    latitude: 37.5340,
    longitude: 127.0005,
    address: '서울 용산구 한남동 200',
    phone: '02-5555-1234',
    photos: [],
    rating: 4.0,
    reviewCount: 89,
    tags: ['셀프주유', '24시간'],
    openingHours: '24시간',
    submittedBy: 'admin',
    approved: true,
    createdAt: '2026-03-01',
  },
];
